// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecondBrain.Infrastructure.Persistence;

#nullable disable

namespace SecondBrain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SecondBrainDbContext))]
    [Migration("20260919003506_AddConceptStructuredFieldsAndCitext")]
    partial class AddConceptStructuredFieldsAndCitext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecondBrain.Domain.Entities.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeExample")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DocumentationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExpectedOutput")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("SimpleAnalogy")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhereUsed")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("concepts", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptNote", b =>
                {
                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConceptId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("concept_notes", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptProject", b =>
                {
                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConceptId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("concept_projects", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptRelation", b =>
                {
                    b.Property<Guid>("SourceConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetConceptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceConceptId", "TargetConceptId", "Type");

                    b.HasIndex("TargetConceptId");

                    b.ToTable("concept_relations", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptTag", b =>
                {
                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConceptId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("concept_tags", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptNote", b =>
                {
                    b.HasOne("SecondBrain.Domain.Entities.Concept", "Concept")
                        .WithMany("ConceptNotes")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecondBrain.Domain.Entities.Note", "Note")
                        .WithMany("ConceptNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptProject", b =>
                {
                    b.HasOne("SecondBrain.Domain.Entities.Concept", "Concept")
                        .WithMany("ConceptProjects")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecondBrain.Domain.Entities.Project", "Project")
                        .WithMany("ConceptProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptRelation", b =>
                {
                    b.HasOne("SecondBrain.Domain.Entities.Concept", "SourceConcept")
                        .WithMany("RelationsAsSource")
                        .HasForeignKey("SourceConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecondBrain.Domain.Entities.Concept", "TargetConcept")
                        .WithMany("RelationsAsTarget")
                        .HasForeignKey("TargetConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceConcept");

                    b.Navigation("TargetConcept");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.ConceptTag", b =>
                {
                    b.HasOne("SecondBrain.Domain.Entities.Concept", "Concept")
                        .WithMany("ConceptTags")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecondBrain.Domain.Entities.Tag", "Tag")
                        .WithMany("ConceptTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Concept", b =>
                {
                    b.Navigation("ConceptNotes");

                    b.Navigation("ConceptProjects");

                    b.Navigation("ConceptTags");

                    b.Navigation("RelationsAsSource");

                    b.Navigation("RelationsAsTarget");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Note", b =>
                {
                    b.Navigation("ConceptNotes");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Project", b =>
                {
                    b.Navigation("ConceptProjects");
                });

            modelBuilder.Entity("SecondBrain.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ConceptTags");
                });
#pragma warning restore 612, 618
        }
    }
}
